# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetUpdateStatusDeviceLiveResponse(UniversalBaseModel):
    update: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seconds since last update
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    "1" = online, "2" = recently online, "3" = offline
    """

    server_time: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current server Unix timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
