# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        DeviceInfo,
        DeviceInfoDevice,
        DeviceInfoValues,
        DeviceProfile,
        DeviceProfileDevice,
        DeviceProfileFollowers,
        DeviceProfileObserver,
        DeviceStats,
        DeviceValues,
        EvolutionResponse,
        EvolutionResponseData,
        EvolutionResponseDataSummaryValue,
        EvolutionResponseDataValuesValueValue,
        EvolutionResponseDataValuesValueValueStats,
        ForecastResponse,
        ForecastResponseForecastValue,
        ForecastResponseForecastValueTemperature,
        ForecastResponseForecastValueWeather,
        ForecastResponseInfo,
        ForecastResponseLocation,
        MapDevicesResponse,
        PageDevice,
        PageDeviceValues,
        PageDevicesResponse,
        TimestampValue,
        WindData,
        WindDataValuesItem,
    )
    from . import auth, device_history, device_live, forecast, map_, metar, stations
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .auth import LoginAuthRequestLoginFormRememberMe
    from .client import AsyncWeathercloudClient, WeathercloudClient
    from .device_history import GetEvolutionDeviceHistoryRequestPeriod
    from .device_live import GetUpdateStatusDeviceLiveResponse
    from .environment import WeathercloudClientEnvironment
    from .map_ import GetMetarsMapResponse
    from .stations import GetPopularStationsRequestPeriod
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncWeathercloudClient": ".client",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "DeviceInfo": ".types",
    "DeviceInfoDevice": ".types",
    "DeviceInfoValues": ".types",
    "DeviceProfile": ".types",
    "DeviceProfileDevice": ".types",
    "DeviceProfileFollowers": ".types",
    "DeviceProfileObserver": ".types",
    "DeviceStats": ".types",
    "DeviceValues": ".types",
    "EvolutionResponse": ".types",
    "EvolutionResponseData": ".types",
    "EvolutionResponseDataSummaryValue": ".types",
    "EvolutionResponseDataValuesValueValue": ".types",
    "EvolutionResponseDataValuesValueValueStats": ".types",
    "ForecastResponse": ".types",
    "ForecastResponseForecastValue": ".types",
    "ForecastResponseForecastValueTemperature": ".types",
    "ForecastResponseForecastValueWeather": ".types",
    "ForecastResponseInfo": ".types",
    "ForecastResponseLocation": ".types",
    "GetEvolutionDeviceHistoryRequestPeriod": ".device_history",
    "GetMetarsMapResponse": ".map_",
    "GetPopularStationsRequestPeriod": ".stations",
    "GetUpdateStatusDeviceLiveResponse": ".device_live",
    "LoginAuthRequestLoginFormRememberMe": ".auth",
    "MapDevicesResponse": ".types",
    "PageDevice": ".types",
    "PageDeviceValues": ".types",
    "PageDevicesResponse": ".types",
    "TimestampValue": ".types",
    "WeathercloudClient": ".client",
    "WeathercloudClientEnvironment": ".environment",
    "WindData": ".types",
    "WindDataValuesItem": ".types",
    "auth": ".auth",
    "device_history": ".device_history",
    "device_live": ".device_live",
    "forecast": ".forecast",
    "map_": ".map_",
    "metar": ".metar",
    "stations": ".stations",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncWeathercloudClient",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "DeviceInfo",
    "DeviceInfoDevice",
    "DeviceInfoValues",
    "DeviceProfile",
    "DeviceProfileDevice",
    "DeviceProfileFollowers",
    "DeviceProfileObserver",
    "DeviceStats",
    "DeviceValues",
    "EvolutionResponse",
    "EvolutionResponseData",
    "EvolutionResponseDataSummaryValue",
    "EvolutionResponseDataValuesValueValue",
    "EvolutionResponseDataValuesValueValueStats",
    "ForecastResponse",
    "ForecastResponseForecastValue",
    "ForecastResponseForecastValueTemperature",
    "ForecastResponseForecastValueWeather",
    "ForecastResponseInfo",
    "ForecastResponseLocation",
    "GetEvolutionDeviceHistoryRequestPeriod",
    "GetMetarsMapResponse",
    "GetPopularStationsRequestPeriod",
    "GetUpdateStatusDeviceLiveResponse",
    "LoginAuthRequestLoginFormRememberMe",
    "MapDevicesResponse",
    "PageDevice",
    "PageDeviceValues",
    "PageDevicesResponse",
    "TimestampValue",
    "WeathercloudClient",
    "WeathercloudClientEnvironment",
    "WindData",
    "WindDataValuesItem",
    "auth",
    "device_history",
    "device_live",
    "forecast",
    "map_",
    "metar",
    "stations",
]
