# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.evolution_response import EvolutionResponse
from .raw_client import AsyncRawDeviceHistoryClient, RawDeviceHistoryClient
from .types.get_evolution_device_history_request_period import GetEvolutionDeviceHistoryRequestPeriod

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DeviceHistoryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDeviceHistoryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDeviceHistoryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDeviceHistoryClient
        """
        return self._raw_client

    def get_evolution(
        self,
        *,
        device: str,
        variable: int,
        period: GetEvolutionDeviceHistoryRequestPeriod,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvolutionResponse:
        """
        Returns hourly aggregated history for a given variable and period.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        **Variable codes:**
        | Code | Sensor |
        |------|--------|
        | 101  | Temperature (°C) |
        | 201  | Humidity (%) |
        | 541  | Dew point (°C) |
        | 641  | Barometric pressure (hPa) |
        | 701  | Wind speed (m/s) |
        | 6001 | Wind direction (°) |
        | 6501 | Wind gust / high speed (m/s) |
        | 801  | Rain (mm) |
        | 811  | Rain rate (mm/h) |
        | 1001 | Solar radiation (W/m²) |
        | 1101 | UV index |

        **Period values:** `day`, `week`, `month`, `year`

        Parameters
        ----------
        device : str

        variable : int

        period : GetEvolutionDeviceHistoryRequestPeriod

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvolutionResponse
            Time-series evolution data

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.device_history.get_evolution(
            device="5726468552",
            variable=101,
            period="day",
        )
        """
        _response = self._raw_client.get_evolution(
            device=device, variable=variable, period=period, request_options=request_options
        )
        return _response.data


class AsyncDeviceHistoryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDeviceHistoryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDeviceHistoryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDeviceHistoryClient
        """
        return self._raw_client

    async def get_evolution(
        self,
        *,
        device: str,
        variable: int,
        period: GetEvolutionDeviceHistoryRequestPeriod,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EvolutionResponse:
        """
        Returns hourly aggregated history for a given variable and period.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        **Variable codes:**
        | Code | Sensor |
        |------|--------|
        | 101  | Temperature (°C) |
        | 201  | Humidity (%) |
        | 541  | Dew point (°C) |
        | 641  | Barometric pressure (hPa) |
        | 701  | Wind speed (m/s) |
        | 6001 | Wind direction (°) |
        | 6501 | Wind gust / high speed (m/s) |
        | 801  | Rain (mm) |
        | 811  | Rain rate (mm/h) |
        | 1001 | Solar radiation (W/m²) |
        | 1101 | UV index |

        **Period values:** `day`, `week`, `month`, `year`

        Parameters
        ----------
        device : str

        variable : int

        period : GetEvolutionDeviceHistoryRequestPeriod

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EvolutionResponse
            Time-series evolution data

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.device_history.get_evolution(
                device="5726468552",
                variable=101,
                period="day",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_evolution(
            device=device, variable=variable, period=period, request_options=request_options
        )
        return _response.data
