# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.evolution_response import EvolutionResponse
from .types.get_evolution_device_history_request_period import GetEvolutionDeviceHistoryRequestPeriod
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawDeviceHistoryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_evolution(
        self,
        *,
        device: str,
        variable: int,
        period: GetEvolutionDeviceHistoryRequestPeriod,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[EvolutionResponse]:
        """
        Returns hourly aggregated history for a given variable and period.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        **Variable codes:**
        | Code | Sensor |
        |------|--------|
        | 101  | Temperature (°C) |
        | 201  | Humidity (%) |
        | 541  | Dew point (°C) |
        | 641  | Barometric pressure (hPa) |
        | 701  | Wind speed (m/s) |
        | 6001 | Wind direction (°) |
        | 6501 | Wind gust / high speed (m/s) |
        | 801  | Rain (mm) |
        | 811  | Rain rate (mm/h) |
        | 1001 | Solar radiation (W/m²) |
        | 1101 | UV index |

        **Period values:** `day`, `week`, `month`, `year`

        Parameters
        ----------
        device : str

        variable : int

        period : GetEvolutionDeviceHistoryRequestPeriod

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[EvolutionResponse]
            Time-series evolution data
        """
        _response = self._client_wrapper.httpx_client.request(
            "device/evolution",
            method="POST",
            data={
                "device": device,
                "variable": variable,
                "period": period,
            },
            headers={
                "content-type": "application/x-www-form-urlencoded",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvolutionResponse,
                    parse_obj_as(
                        type_=EvolutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawDeviceHistoryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_evolution(
        self,
        *,
        device: str,
        variable: int,
        period: GetEvolutionDeviceHistoryRequestPeriod,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[EvolutionResponse]:
        """
        Returns hourly aggregated history for a given variable and period.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        **Variable codes:**
        | Code | Sensor |
        |------|--------|
        | 101  | Temperature (°C) |
        | 201  | Humidity (%) |
        | 541  | Dew point (°C) |
        | 641  | Barometric pressure (hPa) |
        | 701  | Wind speed (m/s) |
        | 6001 | Wind direction (°) |
        | 6501 | Wind gust / high speed (m/s) |
        | 801  | Rain (mm) |
        | 811  | Rain rate (mm/h) |
        | 1001 | Solar radiation (W/m²) |
        | 1101 | UV index |

        **Period values:** `day`, `week`, `month`, `year`

        Parameters
        ----------
        device : str

        variable : int

        period : GetEvolutionDeviceHistoryRequestPeriod

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[EvolutionResponse]
            Time-series evolution data
        """
        _response = await self._client_wrapper.httpx_client.request(
            "device/evolution",
            method="POST",
            data={
                "device": device,
                "variable": variable,
                "period": period,
            },
            headers={
                "content-type": "application/x-www-form-urlencoded",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    EvolutionResponse,
                    parse_obj_as(
                        type_=EvolutionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
