# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.forecast_response import ForecastResponse
from .raw_client import AsyncRawForecastClient, RawForecastClient


class ForecastClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawForecastClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawForecastClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawForecastClient
        """
        return self._raw_client

    def get_daily(self, *, id: str, request_options: typing.Optional[RequestOptions] = None) -> ForecastResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ForecastResponse
            Daily forecast (6 days from WMO)

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.forecast.get_daily(
            id="5726468552",
        )
        """
        _response = self._raw_client.get_daily(id=id, request_options=request_options)
        return _response.data


class AsyncForecastClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawForecastClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawForecastClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawForecastClient
        """
        return self._raw_client

    async def get_daily(self, *, id: str, request_options: typing.Optional[RequestOptions] = None) -> ForecastResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ForecastResponse
            Daily forecast (6 days from WMO)

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.forecast.get_daily(
                id="5726468552",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_daily(id=id, request_options=request_options)
        return _response.data
