# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .device_info import DeviceInfo
    from .device_info_device import DeviceInfoDevice
    from .device_info_values import DeviceInfoValues
    from .device_profile import DeviceProfile
    from .device_profile_device import DeviceProfileDevice
    from .device_profile_followers import DeviceProfileFollowers
    from .device_profile_observer import DeviceProfileObserver
    from .device_stats import DeviceStats
    from .device_values import DeviceValues
    from .evolution_response import EvolutionResponse
    from .evolution_response_data import EvolutionResponseData
    from .evolution_response_data_summary_value import EvolutionResponseDataSummaryValue
    from .evolution_response_data_values_value_value import EvolutionResponseDataValuesValueValue
    from .evolution_response_data_values_value_value_stats import EvolutionResponseDataValuesValueValueStats
    from .forecast_response import ForecastResponse
    from .forecast_response_forecast_value import ForecastResponseForecastValue
    from .forecast_response_forecast_value_temperature import ForecastResponseForecastValueTemperature
    from .forecast_response_forecast_value_weather import ForecastResponseForecastValueWeather
    from .forecast_response_info import ForecastResponseInfo
    from .forecast_response_location import ForecastResponseLocation
    from .map_devices_response import MapDevicesResponse
    from .page_device import PageDevice
    from .page_device_values import PageDeviceValues
    from .page_devices_response import PageDevicesResponse
    from .timestamp_value import TimestampValue
    from .wind_data import WindData
    from .wind_data_values_item import WindDataValuesItem
_dynamic_imports: typing.Dict[str, str] = {
    "DeviceInfo": ".device_info",
    "DeviceInfoDevice": ".device_info_device",
    "DeviceInfoValues": ".device_info_values",
    "DeviceProfile": ".device_profile",
    "DeviceProfileDevice": ".device_profile_device",
    "DeviceProfileFollowers": ".device_profile_followers",
    "DeviceProfileObserver": ".device_profile_observer",
    "DeviceStats": ".device_stats",
    "DeviceValues": ".device_values",
    "EvolutionResponse": ".evolution_response",
    "EvolutionResponseData": ".evolution_response_data",
    "EvolutionResponseDataSummaryValue": ".evolution_response_data_summary_value",
    "EvolutionResponseDataValuesValueValue": ".evolution_response_data_values_value_value",
    "EvolutionResponseDataValuesValueValueStats": ".evolution_response_data_values_value_value_stats",
    "ForecastResponse": ".forecast_response",
    "ForecastResponseForecastValue": ".forecast_response_forecast_value",
    "ForecastResponseForecastValueTemperature": ".forecast_response_forecast_value_temperature",
    "ForecastResponseForecastValueWeather": ".forecast_response_forecast_value_weather",
    "ForecastResponseInfo": ".forecast_response_info",
    "ForecastResponseLocation": ".forecast_response_location",
    "MapDevicesResponse": ".map_devices_response",
    "PageDevice": ".page_device",
    "PageDeviceValues": ".page_device_values",
    "PageDevicesResponse": ".page_devices_response",
    "TimestampValue": ".timestamp_value",
    "WindData": ".wind_data",
    "WindDataValuesItem": ".wind_data_values_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "DeviceInfo",
    "DeviceInfoDevice",
    "DeviceInfoValues",
    "DeviceProfile",
    "DeviceProfileDevice",
    "DeviceProfileFollowers",
    "DeviceProfileObserver",
    "DeviceStats",
    "DeviceValues",
    "EvolutionResponse",
    "EvolutionResponseData",
    "EvolutionResponseDataSummaryValue",
    "EvolutionResponseDataValuesValueValue",
    "EvolutionResponseDataValuesValueValueStats",
    "ForecastResponse",
    "ForecastResponseForecastValue",
    "ForecastResponseForecastValueTemperature",
    "ForecastResponseForecastValueWeather",
    "ForecastResponseInfo",
    "ForecastResponseLocation",
    "MapDevicesResponse",
    "PageDevice",
    "PageDeviceValues",
    "PageDevicesResponse",
    "TimestampValue",
    "WindData",
    "WindDataValuesItem",
]
