# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .device_profile_device import DeviceProfileDevice
from .device_profile_followers import DeviceProfileFollowers
from .device_profile_observer import DeviceProfileObserver


class DeviceProfile(UniversalBaseModel):
    observer: typing.Optional[DeviceProfileObserver] = None
    followers: typing.Optional[DeviceProfileFollowers] = None
    device: typing.Optional[DeviceProfileDevice] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
