# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .device_info_device import DeviceInfoDevice
from .device_info_values import DeviceInfoValues


class DeviceInfo(UniversalBaseModel):
    """
    Station metadata and current sensor snapshot.
    Note: sensor values are returned as strings; unavailable sensors show `-3276.8` / `-32768`.
    """

    device: typing.Optional[DeviceInfoDevice] = None
    values: typing.Optional[DeviceInfoValues] = pydantic.Field(default=None)
    """
    Current sensor readings as strings.
    Unavailable sensors return `"-3276.8"` (float sensors) or `"-32768"` (integer sensors).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
