# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DeviceInfoValues(UniversalBaseModel):
    """
    Current sensor readings as strings.
    Unavailable sensors return `"-3276.8"` (float sensors) or `"-32768"` (integer sensors).
    """

    temp: typing.Optional[str] = pydantic.Field(default=None)
    """
    Temperature (°C)
    """

    hum: typing.Optional[str] = pydantic.Field(default=None)
    """
    Relative humidity (%)
    """

    dew: typing.Optional[str] = pydantic.Field(default=None)
    """
    Dew point (°C)
    """

    wspdavg: typing.Optional[str] = pydantic.Field(default=None)
    """
    Average wind speed (m/s)
    """

    wdiravg: typing.Optional[str] = pydantic.Field(default=None)
    """
    Average wind direction (°)
    """

    bar: typing.Optional[str] = pydantic.Field(default=None)
    """
    Barometric pressure (hPa)
    """

    rain: typing.Optional[str] = pydantic.Field(default=None)
    """
    Total rain (mm)
    """

    rainrate: typing.Optional[str] = pydantic.Field(default=None)
    """
    Rain rate (mm/h)
    """

    solarrad: typing.Optional[str] = pydantic.Field(default=None)
    """
    Solar radiation (W/m²)
    """

    uvi: typing.Optional[str] = pydantic.Field(default=None)
    """
    UV index
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
