# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DeviceStats(UniversalBaseModel):
    """
    Current readings and period statistics for all sensors.
    All values are `[unix_timestamp, value]` tuples (`TimestampValue`).

    **Key pattern:** `{sensor}_{period}_{type}`
    - Sensors: `temp`, `tempin`, `dew`, `chill`, `heat`, `heatin`, `hum`, `humin`, `bar`, `wdir`, `wdiravg`, `wspd`, `wspdavg`, `wspdhi`, `rainrate`, `rain`, `solarrad`, `uvi`
    - Period types: `current`, `day_max`, `day_min`, `month_max`, `month_min`, `year_max`, `year_min`
    - Rain also has: `day_total`, `month_total`, `year_total`
    - Solarrad also has: `day_hours`, `month_hours`, `year_hours`
    """

    last_update: typing.Optional[int] = pydantic.Field(default=None)
    """
    Unix timestamp of last reading
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
