# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DeviceInfoDevice(UniversalBaseModel):
    account: typing.Optional[int] = pydantic.Field(default=None)
    """
    Account type (0 = free)
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    "1" = online, "2" = recently online, "3" = offline
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    City name
    """

    altitude: typing.Optional[str] = pydantic.Field(default=None)
    """
    Altitude in metres (as string)
    """

    image: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL to station photo, or null
    """

    is_webcam: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="isWebcam"), pydantic.Field(alias="isWebcam")
    ] = None
    favorite: typing.Optional[bool] = None
    social: typing.Optional[bool] = None
    update: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seconds since last update
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
