# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .evolution_response_data_summary_value import EvolutionResponseDataSummaryValue
from .evolution_response_data_values_value_value import EvolutionResponseDataValuesValueValue


class EvolutionResponseData(UniversalBaseModel):
    timezone: typing.Optional[str] = None
    summary: typing.Optional[typing.Dict[str, EvolutionResponseDataSummaryValue]] = pydantic.Field(default=None)
    """
    Keyed by variable code (e.g. "101")
    """

    values: typing.Optional[typing.Dict[str, typing.Dict[str, EvolutionResponseDataValuesValueValue]]] = pydantic.Field(
        default=None
    )
    """
    Keyed by Unix timestamp (hour buckets), then by variable code.
    Each entry has `samples` and `stats`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
