# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .forecast_response_forecast_value import ForecastResponseForecastValue
from .forecast_response_info import ForecastResponseInfo
from .forecast_response_location import ForecastResponseLocation


class ForecastResponse(UniversalBaseModel):
    info: typing.Optional[ForecastResponseInfo] = None
    location: typing.Optional[ForecastResponseLocation] = None
    forecast: typing.Optional[typing.Dict[str, ForecastResponseForecastValue]] = pydantic.Field(default=None)
    """
    Keyed by date string (YYYY-MM-DD)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
