# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MapDevicesResponse(UniversalBaseModel):
    """
    Stations as compact arrays. Also contains `owner` and `favorites` arrays (empty unless logged in).
    """

    devices: typing.Optional[typing.List[typing.List[typing.Any]]] = pydantic.Field(default=None)
    """
    Each entry is an array:
    `[id, city, lat, lon, status, 0, temp×10, hum, bar×10, wspd×10, wdir, rainrate×10, rain×10, solarrad×10, uvi×10]`
    
    - `status`: 1=online, 2=recently online, 3=offline
    - Divide index 6 and above by 10 to get real units
    """

    owner: typing.Optional[typing.List[typing.List[typing.Any]]] = pydantic.Field(default=None)
    """
    Owner's own stations (empty if not logged in)
    """

    favorites: typing.Optional[typing.List[typing.List[typing.Any]]] = pydantic.Field(default=None)
    """
    Favourite stations (empty if not logged in)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
