# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PageDeviceValues(UniversalBaseModel):
    """
    Scaled integer sensor readings — divide by 10 for most values.
    e.g. `temp: 281` → 28.1°C, `bar: 10247` → 1024.7 hPa, `uvi: 70` → UV 7.0
    """

    epoch: typing.Optional[str] = None
    temp: typing.Optional[str] = None
    hum: typing.Optional[str] = None
    dew: typing.Optional[str] = None
    chill: typing.Optional[str] = None
    heat: typing.Optional[str] = None
    bar: typing.Optional[str] = None
    wdir: typing.Optional[str] = None
    wspd: typing.Optional[str] = None
    wspdavg: typing.Optional[str] = None
    wspdhi: typing.Optional[str] = None
    rainrate: typing.Optional[str] = None
    rain: typing.Optional[str] = None
    solarrad: typing.Optional[str] = None
    uvi: typing.Optional[str] = None
    tempin: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indoor temperature (°C, scaled ×10) — if sensor present
    """

    humin: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indoor humidity (%, scaled ×10) — if sensor present
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
