# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.map_devices_response import MapDevicesResponse
from .raw_client import AsyncRawMapClient, RawMapClient
from .types.get_metars_map_response import GetMetarsMapResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MapClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMapClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMapClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMapClient
        """
        return self._raw_client

    def get_devices(
        self,
        *,
        user: typing.Optional[str] = OMIT,
        location: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MapDevicesResponse:
        """
        Returns stations visible on the map for a given location bounding box.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        Parameters
        ----------
        user : typing.Optional[str]
            Filter by user (empty = all)

        location : typing.Optional[str]
            lat,lon,zoom format

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MapDevicesResponse
            Stations on the map as arrays of scaled values

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.map_.get_devices()
        """
        _response = self._raw_client.get_devices(user=user, location=location, request_options=request_options)
        return _response.data

    def get_background_devices(
        self, *, user: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> MapDevicesResponse:
        """
        Parameters
        ----------
        user : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MapDevicesResponse
            Inactive/background stations (same array format as /map/devices)

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.map_.get_background_devices()
        """
        _response = self._raw_client.get_background_devices(user=user, request_options=request_options)
        return _response.data

    def get_metars(
        self, *, request: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> GetMetarsMapResponse:
        """
        Parameters
        ----------
        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMetarsMapResponse
            METAR airport observations as arrays

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.map_.get_metars(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.get_metars(request=request, request_options=request_options)
        return _response.data


class AsyncMapClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMapClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMapClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMapClient
        """
        return self._raw_client

    async def get_devices(
        self,
        *,
        user: typing.Optional[str] = OMIT,
        location: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MapDevicesResponse:
        """
        Returns stations visible on the map for a given location bounding box.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        Parameters
        ----------
        user : typing.Optional[str]
            Filter by user (empty = all)

        location : typing.Optional[str]
            lat,lon,zoom format

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MapDevicesResponse
            Stations on the map as arrays of scaled values

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.map_.get_devices()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_devices(user=user, location=location, request_options=request_options)
        return _response.data

    async def get_background_devices(
        self, *, user: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> MapDevicesResponse:
        """
        Parameters
        ----------
        user : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MapDevicesResponse
            Inactive/background stations (same array format as /map/devices)

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.map_.get_background_devices()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_background_devices(user=user, request_options=request_options)
        return _response.data

    async def get_metars(
        self, *, request: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> GetMetarsMapResponse:
        """
        Parameters
        ----------
        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMetarsMapResponse
            METAR airport observations as arrays

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.map_.get_metars(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_metars(request=request, request_options=request_options)
        return _response.data
