# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DeviceValues(UniversalBaseModel):
    """
    Live sensor readings
    """

    epoch: typing.Optional[int] = pydantic.Field(default=None)
    """
    Unix timestamp of reading
    """

    temp: typing.Optional[float] = pydantic.Field(default=None)
    """
    Temperature (°C)
    """

    dew: typing.Optional[float] = pydantic.Field(default=None)
    """
    Dew point (°C)
    """

    chill: typing.Optional[float] = pydantic.Field(default=None)
    """
    Wind chill (°C)
    """

    heat: typing.Optional[float] = pydantic.Field(default=None)
    """
    Heat index (°C)
    """

    hum: typing.Optional[int] = pydantic.Field(default=None)
    """
    Relative humidity (%)
    """

    bar: typing.Optional[float] = pydantic.Field(default=None)
    """
    Barometric pressure (hPa)
    """

    wdir: typing.Optional[int] = pydantic.Field(default=None)
    """
    Instantaneous wind direction (°)
    """

    wdiravg: typing.Optional[int] = pydantic.Field(default=None)
    """
    Average wind direction (°)
    """

    wspd: typing.Optional[float] = pydantic.Field(default=None)
    """
    Instantaneous wind speed (m/s)
    """

    wspdavg: typing.Optional[float] = pydantic.Field(default=None)
    """
    Average wind speed (m/s)
    """

    wspdhi: typing.Optional[float] = pydantic.Field(default=None)
    """
    Wind gust / high speed (m/s)
    """

    rainrate: typing.Optional[float] = pydantic.Field(default=None)
    """
    Rain rate (mm/h)
    """

    rain: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total rain (mm)
    """

    solarrad: typing.Optional[float] = pydantic.Field(default=None)
    """
    Solar radiation (W/m²)
    """

    uvi: typing.Optional[float] = pydantic.Field(default=None)
    """
    UV index (standard units, not ×10 — can be fractional, e.g. 0.9)
    """

    tempin: typing.Optional[float] = pydantic.Field(default=None)
    """
    Inside temperature (°C) — requires authentication
    """

    humin: typing.Optional[int] = pydantic.Field(default=None)
    """
    Inside relative humidity (%) — requires authentication
    """

    heatin: typing.Optional[float] = pydantic.Field(default=None)
    """
    Inside heat index (°C) — requires authentication
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
