# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .forecast_response_forecast_value_temperature import ForecastResponseForecastValueTemperature
from .forecast_response_forecast_value_weather import ForecastResponseForecastValueWeather


class ForecastResponseForecastValue(UniversalBaseModel):
    weather: typing.Optional[ForecastResponseForecastValueWeather] = None
    temperature: typing.Optional[ForecastResponseForecastValueTemperature] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
