# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .page_device_values import PageDeviceValues


class PageDevice(UniversalBaseModel):
    """
    Station entry returned by page/coordinates
    """

    type: typing.Optional[str] = None
    code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Device ID (numeric string)
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Station name as set by the owner
    """

    city: typing.Optional[str] = None
    latitude: typing.Optional[str] = None
    longitude: typing.Optional[str] = None
    elevation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Altitude in metres
    """

    image: typing.Optional[str] = None
    is_webcam: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="isWebcam"), pydantic.Field(alias="isWebcam")
    ] = None
    account: typing.Optional[int] = None
    is_favorite: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="isFavorite"), pydantic.Field(alias="isFavorite")
    ] = None
    update: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seconds since last update
    """

    data: typing.Optional[str] = pydantic.Field(default=None)
    """
    Distance from query point (km)
    """

    values: typing.Optional[PageDeviceValues] = pydantic.Field(default=None)
    """
    Scaled integer sensor readings — divide by 10 for most values.
    e.g. `temp: 281` → 28.1°C, `bar: 10247` → 1024.7 hPa, `uvi: 70` → UV 7.0
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
