# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .wind_data_values_item import WindDataValuesItem


class WindData(UniversalBaseModel):
    date: typing.Optional[int] = pydantic.Field(default=None)
    """
    Unix timestamp (start of period)
    """

    values: typing.Optional[typing.List[WindDataValuesItem]] = pydantic.Field(default=None)
    """
    16 compass directions, each with sum and scale array
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
