# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.page_devices_response import PageDevicesResponse
from .raw_client import AsyncRawStationsClient, RawStationsClient
from .types.get_popular_stations_request_period import GetPopularStationsRequestPeriod


class StationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStationsClient
        """
        return self._raw_client

    def get_nearby(
        self, *, lat: float, lon: float, km: int, request_options: typing.Optional[RequestOptions] = None
    ) -> PageDevicesResponse:
        """
        Returns nearby stations as JSON (despite `text/html` content-type header).
        All `page/*` endpoints return `PageDevice` objects that include the **station name**.
        Values are scaled integers — divide by 10 (e.g. `temp: 281` = 28.1°C).

        Parameters
        ----------
        lat : float

        lon : float

        km : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Nearby stations with name, coordinates and current values

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.stations.get_nearby(
            lat=1.1,
            lon=1.1,
            km=1,
        )
        """
        _response = self._raw_client.get_nearby(lat=lat, lon=lon, km=km, request_options=request_options)
        return _response.data

    def get_popular(
        self,
        *,
        country: str,
        period: GetPopularStationsRequestPeriod,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PageDevicesResponse:
        """
        Parameters
        ----------
        country : str

        period : GetPopularStationsRequestPeriod

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Popular stations with name and current values

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.stations.get_popular(
            country="BE",
            period="day",
        )
        """
        _response = self._raw_client.get_popular(country=country, period=period, request_options=request_options)
        return _response.data

    def get_newest(
        self, *, country: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PageDevicesResponse:
        """
        Parameters
        ----------
        country : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Newest stations with name and current values

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.stations.get_newest(
            country="BE",
        )
        """
        _response = self._raw_client.get_newest(country=country, request_options=request_options)
        return _response.data

    def get_most_followed(
        self, *, country: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PageDevicesResponse:
        """
        Parameters
        ----------
        country : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Most followed stations with name and current values

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.stations.get_most_followed(
            country="BE",
        )
        """
        _response = self._raw_client.get_most_followed(country=country, request_options=request_options)
        return _response.data

    def get_last_views(self, *, request_options: typing.Optional[RequestOptions] = None) -> PageDevicesResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Last viewed stations (empty array if not logged in)

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.stations.get_last_views()
        """
        _response = self._raw_client.get_last_views(request_options=request_options)
        return _response.data

    def get_own(self, *, request_options: typing.Optional[RequestOptions] = None) -> PageDevicesResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Your stations (empty array if not logged in)

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.stations.get_own()
        """
        _response = self._raw_client.get_own(request_options=request_options)
        return _response.data

    def get_station_page(self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None) -> str:
        """
        The station **name** is not available from any JSON API endpoint.
        The easiest way to get it is to fetch the station's HTML page and extract
        the name from the `<title>` or `og:title` meta tag.

        **Example response title:**
        ```
        WeatherStation Skyline - Weathercloud | Global network of weather stations
        ```

        Strip everything from ` - Weathercloud` onward to get the clean station name.

        > This is a plain HTML page, not a JSON API. Use it for scraping only.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            HTML page — extract station name from `<title>` or `<meta property="og:title">`

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.stations.get_station_page(
            device_id="deviceId",
        )
        """
        _response = self._raw_client.get_station_page(device_id=device_id, request_options=request_options)
        return _response.data


class AsyncStationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStationsClient
        """
        return self._raw_client

    async def get_nearby(
        self, *, lat: float, lon: float, km: int, request_options: typing.Optional[RequestOptions] = None
    ) -> PageDevicesResponse:
        """
        Returns nearby stations as JSON (despite `text/html` content-type header).
        All `page/*` endpoints return `PageDevice` objects that include the **station name**.
        Values are scaled integers — divide by 10 (e.g. `temp: 281` = 28.1°C).

        Parameters
        ----------
        lat : float

        lon : float

        km : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Nearby stations with name, coordinates and current values

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.stations.get_nearby(
                lat=1.1,
                lon=1.1,
                km=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_nearby(lat=lat, lon=lon, km=km, request_options=request_options)
        return _response.data

    async def get_popular(
        self,
        *,
        country: str,
        period: GetPopularStationsRequestPeriod,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PageDevicesResponse:
        """
        Parameters
        ----------
        country : str

        period : GetPopularStationsRequestPeriod

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Popular stations with name and current values

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.stations.get_popular(
                country="BE",
                period="day",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_popular(country=country, period=period, request_options=request_options)
        return _response.data

    async def get_newest(
        self, *, country: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PageDevicesResponse:
        """
        Parameters
        ----------
        country : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Newest stations with name and current values

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.stations.get_newest(
                country="BE",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_newest(country=country, request_options=request_options)
        return _response.data

    async def get_most_followed(
        self, *, country: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PageDevicesResponse:
        """
        Parameters
        ----------
        country : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Most followed stations with name and current values

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.stations.get_most_followed(
                country="BE",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_most_followed(country=country, request_options=request_options)
        return _response.data

    async def get_last_views(self, *, request_options: typing.Optional[RequestOptions] = None) -> PageDevicesResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Last viewed stations (empty array if not logged in)

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.stations.get_last_views()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_last_views(request_options=request_options)
        return _response.data

    async def get_own(self, *, request_options: typing.Optional[RequestOptions] = None) -> PageDevicesResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageDevicesResponse
            Your stations (empty array if not logged in)

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.stations.get_own()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_own(request_options=request_options)
        return _response.data

    async def get_station_page(self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None) -> str:
        """
        The station **name** is not available from any JSON API endpoint.
        The easiest way to get it is to fetch the station's HTML page and extract
        the name from the `<title>` or `og:title` meta tag.

        **Example response title:**
        ```
        WeatherStation Skyline - Weathercloud | Global network of weather stations
        ```

        Strip everything from ` - Weathercloud` onward to get the clean station name.

        > This is a plain HTML page, not a JSON API. Use it for scraping only.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            HTML page — extract station name from `<title>` or `<meta property="og:title">`

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.stations.get_station_page(
                device_id="deviceId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_station_page(device_id=device_id, request_options=request_options)
        return _response.data
