# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.page_devices_response import PageDevicesResponse
from .types.get_popular_stations_request_period import GetPopularStationsRequestPeriod
from pydantic import ValidationError


class RawStationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_nearby(
        self, *, lat: float, lon: float, km: int, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PageDevicesResponse]:
        """
        Returns nearby stations as JSON (despite `text/html` content-type header).
        All `page/*` endpoints return `PageDevice` objects that include the **station name**.
        Values are scaled integers — divide by 10 (e.g. `temp: 281` = 28.1°C).

        Parameters
        ----------
        lat : float

        lon : float

        km : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PageDevicesResponse]
            Nearby stations with name, coordinates and current values
        """
        _response = self._client_wrapper.httpx_client.request(
            f"page/coordinates/latitude/{encode_path_param(lat)}/longitude/{encode_path_param(lon)}/distance/{encode_path_param(km)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_popular(
        self,
        *,
        country: str,
        period: GetPopularStationsRequestPeriod,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PageDevicesResponse]:
        """
        Parameters
        ----------
        country : str

        period : GetPopularStationsRequestPeriod

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PageDevicesResponse]
            Popular stations with name and current values
        """
        _response = self._client_wrapper.httpx_client.request(
            f"page/popular/country/{encode_path_param(country)}/period/{encode_path_param(period)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_newest(
        self, *, country: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PageDevicesResponse]:
        """
        Parameters
        ----------
        country : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PageDevicesResponse]
            Newest stations with name and current values
        """
        _response = self._client_wrapper.httpx_client.request(
            f"page/newest/country/{encode_path_param(country)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_most_followed(
        self, *, country: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PageDevicesResponse]:
        """
        Parameters
        ----------
        country : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PageDevicesResponse]
            Most followed stations with name and current values
        """
        _response = self._client_wrapper.httpx_client.request(
            f"page/followers/country/{encode_path_param(country)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_last_views(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PageDevicesResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PageDevicesResponse]
            Last viewed stations (empty array if not logged in)
        """
        _response = self._client_wrapper.httpx_client.request(
            "page/lastviews",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_own(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[PageDevicesResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PageDevicesResponse]
            Your stations (empty array if not logged in)
        """
        _response = self._client_wrapper.httpx_client.request(
            "page/own",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_station_page(
        self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[str]:
        """
        The station **name** is not available from any JSON API endpoint.
        The easiest way to get it is to fetch the station's HTML page and extract
        the name from the `<title>` or `og:title` meta tag.

        **Example response title:**
        ```
        WeatherStation Skyline - Weathercloud | Global network of weather stations
        ```

        Strip everything from ` - Weathercloud` onward to get the clean station name.

        > This is a plain HTML page, not a JSON API. Use it for scraping only.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[str]
            HTML page — extract station name from `<title>` or `<meta property="og:title">`
        """
        _response = self._client_wrapper.httpx_client.request(
            f"d{encode_path_param(device_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=_response.text)  # type: ignore
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawStationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_nearby(
        self, *, lat: float, lon: float, km: int, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PageDevicesResponse]:
        """
        Returns nearby stations as JSON (despite `text/html` content-type header).
        All `page/*` endpoints return `PageDevice` objects that include the **station name**.
        Values are scaled integers — divide by 10 (e.g. `temp: 281` = 28.1°C).

        Parameters
        ----------
        lat : float

        lon : float

        km : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PageDevicesResponse]
            Nearby stations with name, coordinates and current values
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"page/coordinates/latitude/{encode_path_param(lat)}/longitude/{encode_path_param(lon)}/distance/{encode_path_param(km)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_popular(
        self,
        *,
        country: str,
        period: GetPopularStationsRequestPeriod,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PageDevicesResponse]:
        """
        Parameters
        ----------
        country : str

        period : GetPopularStationsRequestPeriod

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PageDevicesResponse]
            Popular stations with name and current values
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"page/popular/country/{encode_path_param(country)}/period/{encode_path_param(period)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_newest(
        self, *, country: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PageDevicesResponse]:
        """
        Parameters
        ----------
        country : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PageDevicesResponse]
            Newest stations with name and current values
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"page/newest/country/{encode_path_param(country)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_most_followed(
        self, *, country: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PageDevicesResponse]:
        """
        Parameters
        ----------
        country : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PageDevicesResponse]
            Most followed stations with name and current values
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"page/followers/country/{encode_path_param(country)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_last_views(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PageDevicesResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PageDevicesResponse]
            Last viewed stations (empty array if not logged in)
        """
        _response = await self._client_wrapper.httpx_client.request(
            "page/lastviews",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_own(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PageDevicesResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PageDevicesResponse]
            Your stations (empty array if not logged in)
        """
        _response = await self._client_wrapper.httpx_client.request(
            "page/own",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PageDevicesResponse,
                    parse_obj_as(
                        type_=PageDevicesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_station_page(
        self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[str]:
        """
        The station **name** is not available from any JSON API endpoint.
        The easiest way to get it is to fetch the station's HTML page and extract
        the name from the `<title>` or `og:title` meta tag.

        **Example response title:**
        ```
        WeatherStation Skyline - Weathercloud | Global network of weather stations
        ```

        Strip everything from ` - Weathercloud` onward to get the clean station name.

        > This is a plain HTML page, not a JSON API. Use it for scraping only.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[str]
            HTML page — extract station name from `<title>` or `<meta property="og:title">`
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"d{encode_path_param(device_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=_response.text)  # type: ignore
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
