# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.device_info import DeviceInfo
from ..types.device_profile import DeviceProfile
from ..types.device_stats import DeviceStats
from ..types.device_values import DeviceValues
from ..types.wind_data import WindData
from .types.get_update_status_device_live_response import GetUpdateStatusDeviceLiveResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawDeviceLiveClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_values(
        self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeviceValues]:
        """
        Returns the latest sensor values for a device. **No CSRF token needed.**
        This is the primary endpoint for a Home Assistant sensor integration.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeviceValues]
            Current weather readings
        """
        _response = self._client_wrapper.httpx_client.request(
            f"device/values/{encode_path_param(device_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeviceValues,
                    parse_obj_as(
                        type_=DeviceValues,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_stats(
        self, *, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeviceStats]:
        """
        Returns current values plus day/month/year min and max for all sensors.
        Each value is a `[unix_timestamp, value]` tuple.

        Parameters
        ----------
        code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeviceStats]
            Statistics for all sensors
        """
        _response = self._client_wrapper.httpx_client.request(
            "device/stats",
            method="GET",
            params={
                "code": code,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeviceStats,
                    parse_obj_as(
                        type_=DeviceStats,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_info(
        self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeviceInfo]:
        """
        Station name, location, elevation, equipment info.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeviceInfo]
            Station metadata
        """
        _response = self._client_wrapper.httpx_client.request(
            f"device/info/{encode_path_param(device_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeviceInfo,
                    parse_obj_as(
                        type_=DeviceInfo,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_wind_rose(
        self, *, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WindData]:
        """
        Wind direction distribution data for the wind rose chart.

        Parameters
        ----------
        code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WindData]
            Wind rose data
        """
        _response = self._client_wrapper.httpx_client.request(
            "device/wind",
            method="GET",
            params={
                "code": code,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WindData,
                    parse_obj_as(
                        type_=WindData,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_update_status(
        self, *, d: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetUpdateStatusDeviceLiveResponse]:
        """
        Returns seconds since last update and device online status.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        Parameters
        ----------
        d : str
            Device ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetUpdateStatusDeviceLiveResponse]
            Update date info
        """
        _response = self._client_wrapper.httpx_client.request(
            "device/ajaxupdatedate",
            method="POST",
            data={
                "d": d,
            },
            headers={
                "content-type": "application/x-www-form-urlencoded",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetUpdateStatusDeviceLiveResponse,
                    parse_obj_as(
                        type_=GetUpdateStatusDeviceLiveResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_owner_profile(
        self, *, d: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeviceProfile]:
        """
        Returns observer name, follower count, and device brand/model.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        Parameters
        ----------
        d : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeviceProfile]
            Profile info
        """
        _response = self._client_wrapper.httpx_client.request(
            "device/ajaxprofile",
            method="POST",
            data={
                "d": d,
            },
            headers={
                "content-type": "application/x-www-form-urlencoded",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeviceProfile,
                    parse_obj_as(
                        type_=DeviceProfile,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawDeviceLiveClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_values(
        self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeviceValues]:
        """
        Returns the latest sensor values for a device. **No CSRF token needed.**
        This is the primary endpoint for a Home Assistant sensor integration.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeviceValues]
            Current weather readings
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"device/values/{encode_path_param(device_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeviceValues,
                    parse_obj_as(
                        type_=DeviceValues,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_stats(
        self, *, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeviceStats]:
        """
        Returns current values plus day/month/year min and max for all sensors.
        Each value is a `[unix_timestamp, value]` tuple.

        Parameters
        ----------
        code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeviceStats]
            Statistics for all sensors
        """
        _response = await self._client_wrapper.httpx_client.request(
            "device/stats",
            method="GET",
            params={
                "code": code,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeviceStats,
                    parse_obj_as(
                        type_=DeviceStats,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_info(
        self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeviceInfo]:
        """
        Station name, location, elevation, equipment info.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeviceInfo]
            Station metadata
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"device/info/{encode_path_param(device_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeviceInfo,
                    parse_obj_as(
                        type_=DeviceInfo,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_wind_rose(
        self, *, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WindData]:
        """
        Wind direction distribution data for the wind rose chart.

        Parameters
        ----------
        code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WindData]
            Wind rose data
        """
        _response = await self._client_wrapper.httpx_client.request(
            "device/wind",
            method="GET",
            params={
                "code": code,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WindData,
                    parse_obj_as(
                        type_=WindData,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_update_status(
        self, *, d: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetUpdateStatusDeviceLiveResponse]:
        """
        Returns seconds since last update and device online status.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        Parameters
        ----------
        d : str
            Device ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetUpdateStatusDeviceLiveResponse]
            Update date info
        """
        _response = await self._client_wrapper.httpx_client.request(
            "device/ajaxupdatedate",
            method="POST",
            data={
                "d": d,
            },
            headers={
                "content-type": "application/x-www-form-urlencoded",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetUpdateStatusDeviceLiveResponse,
                    parse_obj_as(
                        type_=GetUpdateStatusDeviceLiveResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_owner_profile(
        self, *, d: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeviceProfile]:
        """
        Returns observer name, follower count, and device brand/model.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        Parameters
        ----------
        d : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeviceProfile]
            Profile info
        """
        _response = await self._client_wrapper.httpx_client.request(
            "device/ajaxprofile",
            method="POST",
            data={
                "d": d,
            },
            headers={
                "content-type": "application/x-www-form-urlencoded",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeviceProfile,
                    parse_obj_as(
                        type_=DeviceProfile,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
