# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAuthClient, RawAuthClient
from .types.login_auth_request_login_form_remember_me import LoginAuthRequestLoginFormRememberMe

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AuthClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAuthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAuthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAuthClient
        """
        return self._raw_client

    def login(
        self,
        *,
        login_form_entity: str,
        login_form_password: str,
        login_form_remember_me: typing.Optional[LoginAuthRequestLoginFormRememberMe] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Authenticates a user session to allow viewing private indoor sensors (`tempin`, `humin`, `heatin`) for the user's station.
        This endpoint expects form urlencoded data and returns a `302 Found` redirect on successful login.

        Parameters
        ----------
        login_form_entity : str
            Username or email address

        login_form_password : str
            Account password

        login_form_remember_me : typing.Optional[LoginAuthRequestLoginFormRememberMe]
            Keep the user logged in

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.auth.login(
            login_form_entity="LoginForm[entity]",
            login_form_password="LoginForm[password]",
        )
        """
        _response = self._raw_client.login(
            login_form_entity=login_form_entity,
            login_form_password=login_form_password,
            login_form_remember_me=login_form_remember_me,
            request_options=request_options,
        )
        return _response.data


class AsyncAuthClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAuthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAuthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAuthClient
        """
        return self._raw_client

    async def login(
        self,
        *,
        login_form_entity: str,
        login_form_password: str,
        login_form_remember_me: typing.Optional[LoginAuthRequestLoginFormRememberMe] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Authenticates a user session to allow viewing private indoor sensors (`tempin`, `humin`, `heatin`) for the user's station.
        This endpoint expects form urlencoded data and returns a `302 Found` redirect on successful login.

        Parameters
        ----------
        login_form_entity : str
            Username or email address

        login_form_password : str
            Account password

        login_form_remember_me : typing.Optional[LoginAuthRequestLoginFormRememberMe]
            Keep the user logged in

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.auth.login(
                login_form_entity="LoginForm[entity]",
                login_form_password="LoginForm[password]",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.login(
            login_form_entity=login_form_entity,
            login_form_password=login_form_password,
            login_form_remember_me=login_form_remember_me,
            request_options=request_options,
        )
        return _response.data
