# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from .types.login_auth_request_login_form_remember_me import LoginAuthRequestLoginFormRememberMe
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAuthClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def login(
        self,
        *,
        login_form_entity: str,
        login_form_password: str,
        login_form_remember_me: typing.Optional[LoginAuthRequestLoginFormRememberMe] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[None]:
        """
        Authenticates a user session to allow viewing private indoor sensors (`tempin`, `humin`, `heatin`) for the user's station.
        This endpoint expects form urlencoded data and returns a `302 Found` redirect on successful login.

        Parameters
        ----------
        login_form_entity : str
            Username or email address

        login_form_password : str
            Account password

        login_form_remember_me : typing.Optional[LoginAuthRequestLoginFormRememberMe]
            Keep the user logged in

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            "signin",
            method="POST",
            data={
                "LoginForm[entity]": login_form_entity,
                "LoginForm[password]": login_form_password,
                "LoginForm[rememberMe]": login_form_remember_me,
            },
            headers={
                "content-type": "application/x-www-form-urlencoded",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAuthClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def login(
        self,
        *,
        login_form_entity: str,
        login_form_password: str,
        login_form_remember_me: typing.Optional[LoginAuthRequestLoginFormRememberMe] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[None]:
        """
        Authenticates a user session to allow viewing private indoor sensors (`tempin`, `humin`, `heatin`) for the user's station.
        This endpoint expects form urlencoded data and returns a `302 Found` redirect on successful login.

        Parameters
        ----------
        login_form_entity : str
            Username or email address

        login_form_password : str
            Account password

        login_form_remember_me : typing.Optional[LoginAuthRequestLoginFormRememberMe]
            Keep the user logged in

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "signin",
            method="POST",
            data={
                "LoginForm[entity]": login_form_entity,
                "LoginForm[password]": login_form_password,
                "LoginForm[rememberMe]": login_form_remember_me,
            },
            headers={
                "content-type": "application/x-www-form-urlencoded",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
