# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.device_info import DeviceInfo
from ..types.device_profile import DeviceProfile
from ..types.device_stats import DeviceStats
from ..types.device_values import DeviceValues
from ..types.wind_data import WindData
from .raw_client import AsyncRawDeviceLiveClient, RawDeviceLiveClient
from .types.get_update_status_device_live_response import GetUpdateStatusDeviceLiveResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DeviceLiveClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDeviceLiveClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDeviceLiveClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDeviceLiveClient
        """
        return self._raw_client

    def get_values(self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None) -> DeviceValues:
        """
        Returns the latest sensor values for a device. **No CSRF token needed.**
        This is the primary endpoint for a Home Assistant sensor integration.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceValues
            Current weather readings

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.device_live.get_values(
            device_id="5726468552",
        )
        """
        _response = self._raw_client.get_values(device_id=device_id, request_options=request_options)
        return _response.data

    def get_stats(self, *, code: str, request_options: typing.Optional[RequestOptions] = None) -> DeviceStats:
        """
        Returns current values plus day/month/year min and max for all sensors.
        Each value is a `[unix_timestamp, value]` tuple.

        Parameters
        ----------
        code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceStats
            Statistics for all sensors

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.device_live.get_stats(
            code="5726468552",
        )
        """
        _response = self._raw_client.get_stats(code=code, request_options=request_options)
        return _response.data

    def get_info(self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None) -> DeviceInfo:
        """
        Station name, location, elevation, equipment info.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceInfo
            Station metadata

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.device_live.get_info(
            device_id="5726468552",
        )
        """
        _response = self._raw_client.get_info(device_id=device_id, request_options=request_options)
        return _response.data

    def get_wind_rose(self, *, code: str, request_options: typing.Optional[RequestOptions] = None) -> WindData:
        """
        Wind direction distribution data for the wind rose chart.

        Parameters
        ----------
        code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WindData
            Wind rose data

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.device_live.get_wind_rose(
            code="5726468552",
        )
        """
        _response = self._raw_client.get_wind_rose(code=code, request_options=request_options)
        return _response.data

    def get_update_status(
        self, *, d: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GetUpdateStatusDeviceLiveResponse:
        """
        Returns seconds since last update and device online status.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        Parameters
        ----------
        d : str
            Device ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUpdateStatusDeviceLiveResponse
            Update date info

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.device_live.get_update_status(
            d="5726468552",
        )
        """
        _response = self._raw_client.get_update_status(d=d, request_options=request_options)
        return _response.data

    def get_owner_profile(self, *, d: str, request_options: typing.Optional[RequestOptions] = None) -> DeviceProfile:
        """
        Returns observer name, follower count, and device brand/model.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        Parameters
        ----------
        d : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceProfile
            Profile info

        Examples
        --------
        from weathercloud import WeathercloudClient

        client = WeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )
        client.device_live.get_owner_profile(
            d="5726468552",
        )
        """
        _response = self._raw_client.get_owner_profile(d=d, request_options=request_options)
        return _response.data


class AsyncDeviceLiveClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDeviceLiveClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDeviceLiveClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDeviceLiveClient
        """
        return self._raw_client

    async def get_values(
        self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DeviceValues:
        """
        Returns the latest sensor values for a device. **No CSRF token needed.**
        This is the primary endpoint for a Home Assistant sensor integration.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceValues
            Current weather readings

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.device_live.get_values(
                device_id="5726468552",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_values(device_id=device_id, request_options=request_options)
        return _response.data

    async def get_stats(self, *, code: str, request_options: typing.Optional[RequestOptions] = None) -> DeviceStats:
        """
        Returns current values plus day/month/year min and max for all sensors.
        Each value is a `[unix_timestamp, value]` tuple.

        Parameters
        ----------
        code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceStats
            Statistics for all sensors

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.device_live.get_stats(
                code="5726468552",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_stats(code=code, request_options=request_options)
        return _response.data

    async def get_info(self, *, device_id: str, request_options: typing.Optional[RequestOptions] = None) -> DeviceInfo:
        """
        Station name, location, elevation, equipment info.

        Parameters
        ----------
        device_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceInfo
            Station metadata

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.device_live.get_info(
                device_id="5726468552",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_info(device_id=device_id, request_options=request_options)
        return _response.data

    async def get_wind_rose(self, *, code: str, request_options: typing.Optional[RequestOptions] = None) -> WindData:
        """
        Wind direction distribution data for the wind rose chart.

        Parameters
        ----------
        code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WindData
            Wind rose data

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.device_live.get_wind_rose(
                code="5726468552",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_wind_rose(code=code, request_options=request_options)
        return _response.data

    async def get_update_status(
        self, *, d: str, request_options: typing.Optional[RequestOptions] = None
    ) -> GetUpdateStatusDeviceLiveResponse:
        """
        Returns seconds since last update and device online status.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        Parameters
        ----------
        d : str
            Device ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetUpdateStatusDeviceLiveResponse
            Update date info

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.device_live.get_update_status(
                d="5726468552",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_update_status(d=d, request_options=request_options)
        return _response.data

    async def get_owner_profile(
        self, *, d: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DeviceProfile:
        """
        Returns observer name, follower count, and device brand/model.

        > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.

        Parameters
        ----------
        d : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceProfile
            Profile info

        Examples
        --------
        import asyncio

        from weathercloud import AsyncWeathercloudClient

        client = AsyncWeathercloudClient(
            requested_with="YOUR_REQUESTED_WITH",
        )


        async def main() -> None:
            await client.device_live.get_owner_profile(
                d="5726468552",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_owner_profile(d=d, request_options=request_options)
        return _response.data
